### ISSUE TITLE
suggest other headers

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/queuebos-web#36]
@NadhirahIzzati 
- [ ] try to look at other inspirations for header & give suggestions below. Sir would like a different header style.
- [x] update tagline to `Empowering Wait Times`
![image](https://github.com/phisoft/queuebos-web/assets/30463117/244fb812-ac80-4bf6-99a0-e7e3664a9610)

few samples from sir:
![image](https://github.com/phisoft/queuebos-web/assets/30463117/a154ca50-cdfc-47e2-adcf-39635e9d5e66)

**Comment by NadhirahIzzati** [comment]
header 1: 
![Screenshot (43)](https://github.com/phisoft/queuebos-web/assets/74038076/116c71fe-7e47-4927-a10f-80a905f042fd)



![ezgif-2-52f0bfc484](https://github.com/phisoft/queuebos-web/assets/74038076/6e585058-5f91-43e0-92f9-be21ac18268c)

header 2:

![Screenshot (46)](https://github.com/phisoft/queuebos-web/assets/74038076/2efecf5c-d518-4b46-850c-438dba406caa)

header 3: 
![Screenshot (48)](https://github.com/phisoft/queuebos-web/assets/74038076/cbfe6481-9400-4638-8868-40facf2ac3fd)


header 4: 
![Screenshot (49)](https://github.com/phisoft/queuebos-web/assets/74038076/35e23dd9-0f1c-4961-99aa-f5f1a48911d2)
