### ISSUE TITLE
update website layout

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/queuebos-web#44]
https://www.qmatic.com/solutions/queue-management/
https://qwaiting.com/

**Comment by FaziraFM** [comment]
(UI Layout Testing etc)
https://www.figma.com/file/85IWbmoe8Kz9wrFDBhfXn9/QueueBoss-(Test%2FInfo-src)?type=design&node-id=0%3A1&mode=design&t=0tN7E3XB6S3DPZ6V-1

(Copywrited)
https://www.figma.com/file/9omoe8vJKbLKWXAp10d5Uz/QueueBoss-(Copywrited)?type=design&node-id=2%3A9&mode=design&t=CyG7Q0QC7rYS0i96-1

**Comment by FaziraFM** [comment]
(Header Designs)
https://www.figma.com/file/zuw5OFWSAgUf8F5MA15CTL/Header-Designs?type=design&node-id=2%3A33&mode=design&t=SsLnBAHuYKApGdJ3-1

**Comment by FaziraFM** [comment]
I have updated the design according to comments from yesterday

> (Header Designs) https://www.figma.com/file/zuw5OFWSAgUf8F5MA15CTL/Header-Designs?type=design&node-id=2%3A33&mode=design&t=SsLnBAHuYKApGdJ3-1

**Comment by rosclaritha** [comment]
@FaziraFM 
<img width="1055" alt="Screenshot 2023-10-12 at 1 10 44 PM" src="https://github.com/phisoft/queuebos-web/assets/30463117/c851b274-5731-44d5-b17a-a9de0c0d15c1">

use mockup from exisiting, not bankislam:
![image](https://github.com/phisoft/queuebos-web/assets/30463117/2351af95-4cd4-4906-8545-033ed4ea96ad)

**Comment by FaziraFM** [comment]
> @FaziraFM <img alt="Screenshot 2023-10-12 at 1 10 44 PM" width="1055" src="https://user-images.githubusercontent.com/30463117/274487144-c851b274-5731-44d5-b17a-a9de0c0d15c1.png">
> 
> use mockup from exisiting, not bankislam: ![image](https://user-images.githubusercontent.com/30463117/274487238-2351af95-4cd4-4906-8545-033ed4ea96ad.png)

Updated

**Comment by FaziraFM** [comment]
[Header Design Variation]
https://www.figma.com/file/MQyR96ADymD2rf51af5JSz/Header-Design-Variation?type=design&node-id=0%3A1&mode=design&t=VZbCVYKlohwk0Fk7-1

**Comment by russel0907** [comment]
@rosclaritha 

Web Mockup/Template

1. https://dribbble.com/shots/21900100-CMS-Landing-Page-Stay
2. https://dribbble.com/shots/10732914-Srit-Product-Landind-Page/attachments/2549216?mode=media
3. https://recoreru.com/
4. https://dribbble.com/shots/18879480-Taskku-Productivity-Landing-Page
5. https://dribbble.com/shots/19216880-SaaS-Website-Design

**Comment by rosclaritha** [comment]
prepare mockup & redesign of page
