### ISSUE TITLE
change menu design to follow logo theme color

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/queuebos-web#61]
- [x] remove translation options
- [x] change the color to follow logo theme
- [x] change onhover design -> current color is old logo color
- [x] fix view on mobile view

<img width="1622" alt="Screenshot 2023-10-18 at 3 10 58 PM" src="https://github.com/phisoft/queuebos-web/assets/30463117/04810366-600d-459b-911b-2e7a560734d8">

**Comment by FaziraFM** [comment]
- removed translation options
- changed color theme to current logo theme 
- changed on hover design to match current theme
![image](https://github.com/phisoft/queuebos-web/assets/147354657/56d92b66-534e-4cfb-aa61-ba5df86b5763)

- fixed mobile view
![image](https://github.com/phisoft/queuebos-web/assets/147354657/2a4efa85-1480-49e5-82ce-25bd07225714)
