### ISSUE TITLE
create latest image for system images on steps section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/queuebos-web#77]
1. clone `queuebos-addons` to run the system, and see how the system works.
2. go to app, cd app, then run the app by quasar dev to see how the app works.
3. get the latest screenshots & update the system image below:
 
![image](https://github.com/phisoft/queuebos-web/assets/30463117/68c6e24f-5b15-414c-8102-7fdc2402fb5f)

**Comment by FaziraFM** [comment]
![queuebos-mockup-2](https://github.com/phisoft/queuebos-web/assets/147354657/fea6e149-3f46-4854-90d6-6a24776a7881)
![queuebos-mockup-1](https://github.com/phisoft/queuebos-web/assets/147354657/e97e35b9-d155-4b34-9089-86be8224f517)
