### ISSUE TITLE
create latest image for system features in features section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/queuebos-web#78]
need to use the latest system image:
![image](https://github.com/phisoft/queuebos-web/assets/30463117/63b1cdb5-a0b4-481b-bc52-d62fb69c54eb)

update the system screenshot & do a little editing for the system screenshot:

![image](https://github.com/phisoft/queuebos-web/assets/30463117/7bc0cb21-3d55-4b44-af94-94cb623ca898)

**Comment by rosclaritha** [comment]
the latest image put in comment here

**Comment by FaziraFM** [comment]
Counter
![Services-1](https://github.com/phisoft/queuebos-web/assets/147354657/55cffb58-2971-43c1-b649-823a40bd6853)
Example Government Services
![Services-2](https://github.com/phisoft/queuebos-web/assets/147354657/6e73b706-e43d-4553-a395-d453ac5b9efe)
Example Bank Services
![Services-3](https://github.com/phisoft/queuebos-web/assets/147354657/7baa2d8e-d47b-4f21-a018-74b7378044ab)
Example Restaurant Services
![Services-4](https://github.com/phisoft/queuebos-web/assets/147354657/5d5d74dc-c9eb-4220-b8c4-74d8cf2b038a)
Export Examples
![Services-5](https://github.com/phisoft/queuebos-web/assets/147354657/20afa2ba-35fc-4401-a04e-2079f04045ab)
