### ISSUE TITLE
prepare mockup & template for website redesign

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/queuebos-web#83]
@russel0907 
1. find template (if applicable)
2. create mockup of website redesign based on the new template
3. provide link in comment

**Comment by russel0907** [comment]
@rosclaritha 

1. https://dribbble.com/shots/21900100-CMS-Landing-Page-Stay
2. https://dribbble.com/shots/10732914-Srit-Product-Landind-Page/attachments/2549216?mode=media
3. https://dribbble.com/shots/18879480-Taskku-Productivity-Landing-Page
4. https://dribbble.com/shots/19216880-SaaS-Website-Design

Mockup created based on template:
https://www.figma.com/file/kn6KDun1inHSqiRp5hEcPq/QueueBos-Web?type=design&node-id=1%3A4&mode=design&t=jxK0Zr1Suo3BgqgH-1
